export const AF = 'AF'
export const BC = 'BC'
export const DE = 'DE'
export const HL = 'HL'
export const IX = 'IX'
export const IY = 'IY'
export const PC = 'PC'
export const SP = 'SP'

export const ADD = 'ADD'
export const AND = 'AND'
export const CALL = 'CALL'
export const COMP = 'COMP'
export const DEC = 'DEC'
export const HALT = 'HALT'
export const INC = 'INC'
export const JUMP = 'JUMP'
export const LOAD = 'LOAD'
export const NOP = 'NOP'
export const OR = 'OR'
export const POP = 'POP'
export const PUSH = 'PUSH'
export const RET = 'RET'
export const SHL = 'SHL'
export const SHR = 'SHR'
export const SUB = 'SUB'
export const XOR = 'XOR'

