export const MACHINE_TOGGLE_VIDEO = 'MACHINE_TOGGLE_VIDEO'

export const MACHINE_RESET = 'MACHINE_RESET'

export const MACHINE_TRANSITION = 'MACHINE_TRANSITION'

export const MACHINE_COMPILE = 'MACHINE_COMPILE'

export const MACHINE_MOVE_TO_BEGIN = 'MACHINE_MOVE_TO_BEGIN'

export const MACHINE_RUN = 'MACHINE_RUN'

export const MACHINE_STEP_BACKWARD = 'MACHINE_STEP_BACKWARD'

export const MACHINE_STEP_FORWARD = 'MACHINE_STEP_FORWARD'
